name: Bonus2 Build
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        cd calculator2
        make
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: built-artifacts
        path: |
          calculator2/bin/
