name: Build and Publish Docker Container
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build -t bk09/calculator2:latest /home/runner/work/calculator2/super_calcculator/ .
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker Container
      run: docker push your-dockerhub-username/calculator2:latest-container
    - name: Logout from Docker Hub
      run: docker logout
