name: goreleaser

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true
      -  name: Show GoReleaser version
         run: goreleaser -v
      - name: Run GoReleaser
        run: |
          goreleaser release --snapshot --skip-publish
