name: Bonus Notify

on:
  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Notify
      uses: some-notification-action@v1.0
      with:
        message: 'New code pushed to the repository.'
