name: pushed Notification

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest



    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Notify
      uses: some-notification-action@v1
      with:
        message: 'New code pushed to the repository.'
