name: Publication de l'image Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
          
      # Étape 4 : Se connecter sur le hub Docker
      - name: Connection à Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      # Étape 5 : Construire et pousser l'image Docker sur le hub Docker
      - name: Créer et publier l'image Docker
        uses: docker/build-push-action@v2
        with:
          context: ./super_calculator
          file: ./super_calculator/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/super_calculator:latest
